force-app/main/default/objects/Case_Config__c/Case_Config__c.object-meta.xml
<CustomObject>
    <label>Case_Config</label>
    <nameField>
        <displayFormat>CC-{000}</displayFormat>
        <label>Case Config</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case_Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Config__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case_Configs</relationshipLabel>
    <relationshipName>Case_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Config__c/Config__c.object-meta.xml
<CustomObject>
    <label>Config</label>
    <nameField>
        <displayFormat>CN-{000}</displayFormat>
        <label>Config</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/cmp_AvailableConfigs.cls
public with sharing class cmp_AvailableConfigs {

    @AuraEnabled(cacheable=true)
    public static List<Config__c> getAvailableConfigs(){
        String sql = 'SELECT Id, Label__c, Type__c, Amount__c FROM Config__c';
        List<Config__c> c = new List<Config__c>();
        c = Database.query(sql);
        return c;
    }

    @AuraEnabled 
    public static String getCaseStatus(String caseID){
        List<Case> cases = new List<Case>();
        cases = [SELECT Id, Status FROM Case WHERE Id =: caseID];
        String status = cases[0].Status;
        return status;
    }

    @AuraEnabled
    public static List<Case_Config__c> checkCaseConfigs(List<String> configRecords, String recID){
        List<Case_Config__c> caseConfigs = new List<Case_Config__c>();
        caseConfigs = [SELECT Id, Label__c, Case__c FROM Case_Config__c WHERE Label__c IN :configRecords AND Case__c = :recID];
        return caseConfigs;
    }

    @AuraEnabled
    public static string addCaseConfig(List<String> recordDetails, String caseID){
        String msg;
        List<Config__c> configs = [SELECT Id, Label__c, Type__c, Amount__c FROM Config__c WHERE Label__c IN :recordDetails];
        List<Case_Config__c> caseConfigToAdd = new List<Case_Config__c>();
        for(integer i=0; i<configs.size(); i++){
            Case_Config__c cc = new Case_Config__c();
            cc.Label__c = configs[i].Label__c;
            cc.Type__c = configs[i].Type__c;
            cc.Amount__c = configs[i].Amount__c;
            cc.Case__c = caseID;
            caseConfigToAdd.add(cc);
        }
        if(caseConfigToAdd.size() > 0){
            try {
                Database.insert(caseConfigToAdd);
                //insert caseConfigToAdd;
                msg = 'Your selected record are added to Case.';
            } catch (System.DmlException e) {
                msg = e.getMessage();
            }
        }
        return msg;
    }
}