force-app/main/default/objects/Case_Config__c/Case_Config__c.object-meta.xml
<CustomObject>
    <label>Case_Config</label>
    <nameField>
        <displayFormat>CC-{000}</displayFormat>
        <label>Case Config</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case_Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Config__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case_Configs</relationshipLabel>
    <relationshipName>Case_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Config__c/Config__c.object-meta.xml
<CustomObject>
    <label>Config</label>
    <nameField>
        <displayFormat>CN-{000}</displayFormat>
        <label>Config</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/cmp_AvailableConfigsTest.cls
@isTest
public class cmp_AvailableConfigsTest {
    @isTest
    public static void AvailableConfigsUnitTest(){
        
        Test.startTest();
        //create config
        Config__c config = new Config__c();
        config.Label__c = 'Test Label';
        config.Type__c = 'Test Type';
        config.Amount__c = 20.00;
        insert config;
        
        //create case
        Case cases = new Case();
        cases.Subject = 'Test Subject';
        cases.Status = 'Submitted';
        cases.Origin = 'Email';
        insert cases;
        
        //create caseConfig
        Case_Config__c caseConfig = new Case_Config__c();
        caseConfig.Label__c = 'Test Case Lable';
        caseConfig.Type__c = 'Test case type';
        caseConfig.Amount__c = 30.00;
        caseConfig.Case__c = cases.Id;
        insert caseConfig;
        
         Test.stopTest();
        
        //call cmp_AvailableConfigs method
        cmp_AvailableConfigs.getAvailableConfigs();
        
        String caseID = cases.Id;
        cmp_AvailableConfigs.getCaseStatus(caseID);
        
        List<String> checkCaseConfig = new List<String>();
        checkCaseConfig.add(caseConfig.Label__c);
        cmp_AvailableConfigs.checkCaseConfigs(checkCaseConfig, caseID);
        
        List<String> addCaseConfig = new List<String>();
        addCaseConfig.add(config.Label__c);
        cmp_AvailableConfigs.addCaseConfig(addCaseConfig, caseID);
        
        List<String> addCaseConfig1 = new List<String>();
        addCaseConfig1.add(config.Label__c);
        cmp_AvailableConfigs.addCaseConfig(addCaseConfig1, caseID);
        
       
        
    }

}