force-app/main/default/objects/Case_Config__c/Case_Config__c.object-meta.xml
<CustomObject>
    <label>Case_Config</label>
    <nameField>
        <displayFormat>CC-{000}</displayFormat>
        <label>Case Config</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case_Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Config__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case_Configs</relationshipLabel>
    <relationshipName>Case_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/cmp_CaseConfigsTest.cls
@isTest
public class cmp_CaseConfigsTest {
    @isTest
     static void testMakeCallout(){
         
         Test.setMock(HttpCalloutMock.class, new cmp_CaseConfigCalloutMock());
        
        Test.startTest();
        
        Case cases = new Case();
        cases.Subject = 'Test Subject';
        cases.Status = 'Submitted';
        cases.Origin = 'Email';
        insert cases;
        String caseID = cases.Id;
        
        Case_Config__c caseConfig = new Case_Config__c();
        caseConfig.Label__c = 'Test Case Lable';
        caseConfig.Type__c = 'Test case type';
        caseConfig.Amount__c = 30.00;
        caseConfig.Case__c = cases.Id;
        insert caseConfig;
         
         Test.stopTest();
        
        cmp_CaseConfigs.getCaseConfigs(caseID);
        
        cmp_CaseConfigs.updateCaseStatus(caseID);
        
        cmp_CaseConfigs.makePostCallout(caseID);
        
    }

}